CC     = gcc
OPTS   = -Wall -fPIC
INCS   = 
LIBS   = 

SRCS   = LibDisk.c 
OBJS   = $(SRCS:.c=.o)
TARGET = libDisk.so

all: $(TARGET)

clean:
	rm -f $(TARGET) $(OBJS)

%.o: %.c
	$(CC) $(INCS) $(OPTS) -c $< -o $@

$(TARGET): $(OBJS)
	$(CC) -shared -o $(TARGET) $(OBJS) $(LIBS)
