function [Hsa, Hber, Hconst, Hconst2, EVM, Hsa2]=Visualize_init(params)
K=params.K;
numFFT=params.numFFT;
Rs=20e6*K;
Hsa = dsp.SpectrumAnalyzer('SampleRate', 1, ...
    'SpectralAverages', 1, 'SpectrumType', 'Power density', ...
    'PowerUnits', 'dBW', 'Window', 'Rectangular', ...
    'FrequencyResolutionMethod', 'WindowLength', 'WindowLength', numFFT*K,...
    'FFTLengthSource', 'Property', 'FFTLength', numFFT*K*2,...
    'YLimits', [-200 20], 'Position', [168 652 560 420], ...
    'Title', ['FBMC, K = ' num2str(K) ' overlapped symbols'],...
    'PlotAsTwoSidedSpectrum', true);

Hber=comm.ErrorRate;
Hconst=comm.ConstellationDiagram;
Hconst2=clone(Hconst);
Hconst.Position=[6 37 640 460];
Hconst2.Position=[600 37 640 460];
EVM = comm.EVM;
EVM.Normalization = 'Average constellation power';
Hsa2=clone(Hsa);
