function [Hber]=wlanVisualize_init(params)
bw=params.chanBW;
bw=bw(4:end);
numLayer=params.numTx;
myTitle=['WLAN 802.11ac with Bandwidth ',bw,' MHz & ', num2str(numLayer), ' MIMO steams'];  
Hsa = dsp.SpectrumAnalyzer('SampleRate',params.Rs, ...
    'ShowLegend',true, ...
    'Window', 'Rectangular', ...
    'SpectralAverages',10, ...
    'YLimits',[-30 10], ...
    'Position' ,[6 200 800 450], ...
    'Title', myTitle, ...
    'ChannelNames',...
    {'Transmitted','Received Not-Equalized','Received Equalized'});
Hber=comm.ErrorRate;
Hconst=comm.ConstellationDiagram;
Hconst2=clone(Hconst);
Hconst.Position=[6 37 640 460];
Hconst2.Position=[600 37 640 460];
EVM = comm.EVM;
EVM.Normalization = 'Average constellation power';
Hsa2=clone(Hsa);
